//------------------------------------------------------------------------------
// File: main.cpp
//
// Direct3D 8 spinning RGB cube — a multi-project RXDK sample.
//
// The cube geometry (vertices + indices) is generated by BuildColorCube() in the
// "cubemesh" static library (libs/cubemesh), referenced from rxdk.project.json via
// projectReferences. Its public header resolves because the library exports it
// through publicIncludePaths; the code is linked from the library's built .lib.
// The app uploads the mesh into a vertex/index buffer and draws it with a Z-buffer,
// tumbling on two axes.
//------------------------------------------------------------------------------

#include <xtl.h>
#include <stdio.h>
#include <d3d8.h>
#include <d3dx8math.h>

#include "cubemesh.h" // exported by the referenced cubemesh library

namespace {

constexpr DWORD kCubeVertexFvf = D3DFVF_XYZ | D3DFVF_DIFFUSE;

LPDIRECT3D8 g_pD3D = NULL;
LPDIRECT3DDEVICE8 g_pd3dDevice = NULL;
LPDIRECT3DVERTEXBUFFER8 g_pVB = NULL;
LPDIRECT3DINDEXBUFFER8 g_pIB = NULL;

LARGE_INTEGER g_qwLastTime = {};
LARGE_INTEGER g_qwAppTime = {};
LARGE_INTEGER g_qwTicksPerSec = {};
FLOAT g_secsPerTick = 0.0f;

void Cleanup()
{
    if (g_pIB) {
        g_pIB->Release();
        g_pIB = NULL;
    }
    if (g_pVB) {
        g_pVB->Release();
        g_pVB = NULL;
    }
    if (g_pd3dDevice) {
        g_pd3dDevice->Release();
        g_pd3dDevice = NULL;
    }
    if (g_pD3D) {
        g_pD3D->Release();
        g_pD3D = NULL;
    }
}

void InitTime()
{
    QueryPerformanceFrequency(&g_qwTicksPerSec);
    QueryPerformanceCounter(&g_qwLastTime);
    g_secsPerTick = 1.0f / (FLOAT)(LONGLONG)g_qwTicksPerSec.QuadPart;
    g_qwAppTime.QuadPart = 0;
}

void UpdateTime()
{
    LARGE_INTEGER now;
    QueryPerformanceCounter(&now);
    g_qwAppTime.QuadPart += now.QuadPart - g_qwLastTime.QuadPart;
    g_qwLastTime = now;
}

HRESULT InitDevice()
{
    D3DPRESENT_PARAMETERS d3dpp;
    HRESULT hr;

    printf("Creating Direct3D 8 interface\n");
    g_pD3D = Direct3DCreate8(D3D_SDK_VERSION);
    if (!g_pD3D) {
        printf("Failed to create Direct3D 8 interface\n");
        return E_FAIL;
    }

    ZeroMemory(&d3dpp, sizeof(d3dpp));
    d3dpp.BackBufferWidth = 640;
    d3dpp.BackBufferHeight = 480;
    d3dpp.BackBufferFormat = D3DFMT_X8R8G8B8;
    d3dpp.BackBufferCount = 1;
    d3dpp.Windowed = FALSE;
    d3dpp.EnableAutoDepthStencil = TRUE;
    d3dpp.AutoDepthStencilFormat = D3DFMT_D24S8;
    d3dpp.SwapEffect = D3DSWAPEFFECT_DISCARD;
    d3dpp.FullScreen_RefreshRateInHz = 60;
    d3dpp.FullScreen_PresentationInterval = D3DPRESENT_INTERVAL_DEFAULT;

    Direct3D_SetPushBufferSize(512 * 1024, (512 * 1024) / 16);

    printf("Creating HAL device (640x480, Z-buffer)\n");
    hr = Direct3D_CreateDevice(
        D3DADAPTER_DEFAULT,
        D3DDEVTYPE_HAL,
        NULL,
        D3DCREATE_HARDWARE_VERTEXPROCESSING,
        &d3dpp,
        &g_pd3dDevice);
    if (FAILED(hr)) {
        return hr;
    }

    D3DVIEWPORT8 vp = {};
    vp.Width = d3dpp.BackBufferWidth;
    vp.Height = d3dpp.BackBufferHeight;
    vp.MinZ = 0.0f;
    vp.MaxZ = 1.0f;
    hr = g_pd3dDevice->SetViewport(&vp);
    if (FAILED(hr)) {
        return hr;
    }

    printf("Device created\n");
    return S_OK;
}

HRESULT InitTransforms()
{
    D3DXMATRIX matProj;
    D3DXMATRIX matView;
    HRESULT hr;

    D3DXMatrixPerspectiveFovLH(&matProj, D3DX_PI / 4.0f, 4.0f / 3.0f, 1.0f, 200.0f);
    hr = g_pd3dDevice->SetTransform(D3DTS_PROJECTION, &matProj);
    if (FAILED(hr)) {
        return hr;
    }

    {
        const D3DXVECTOR3 eye(0.0f, 0.0f, -6.0f);
        const D3DXVECTOR3 at(0.0f, 0.0f, 0.0f);
        const D3DXVECTOR3 up(0.0f, 1.0f, 0.0f);
        D3DXMatrixLookAtLH(&matView, &eye, &at, &up);
    }
    hr = g_pd3dDevice->SetTransform(D3DTS_VIEW, &matView);
    if (FAILED(hr)) {
        return hr;
    }

    printf("View and projection configured\n");
    return S_OK;
}

HRESULT InitGeometry()
{
    CubeVertex verts[CUBE_VERTEX_COUNT];
    unsigned short indices[CUBE_INDEX_COUNT];
    BuildColorCube(verts, indices, 1.0f); // geometry from the cubemesh library

    HRESULT hr = g_pd3dDevice->CreateVertexBuffer(
        sizeof(verts),
        D3DUSAGE_WRITEONLY,
        kCubeVertexFvf,
        D3DPOOL_MANAGED,
        &g_pVB);
    if (FAILED(hr)) {
        return hr;
    }
    BYTE* pVertices = NULL;
    hr = g_pVB->Lock(0, 0, &pVertices, 0);
    if (FAILED(hr)) {
        return hr;
    }
    memcpy(pVertices, verts, sizeof(verts));
    g_pVB->Unlock();

    hr = g_pd3dDevice->CreateIndexBuffer(
        sizeof(indices),
        D3DUSAGE_WRITEONLY,
        D3DFMT_INDEX16,
        D3DPOOL_MANAGED,
        &g_pIB);
    if (FAILED(hr)) {
        return hr;
    }
    BYTE* pIndices = NULL;
    hr = g_pIB->Lock(0, 0, &pIndices, 0);
    if (FAILED(hr)) {
        return hr;
    }
    memcpy(pIndices, indices, sizeof(indices));
    g_pIB->Unlock();

    printf("Cube mesh created (%d verts, %d indices)\n", CUBE_VERTEX_COUNT, CUBE_INDEX_COUNT);
    return S_OK;
}

void UpdateScene()
{
    const FLOAT secs = (FLOAT)(LONGLONG)g_qwAppTime.QuadPart * g_secsPerTick;
    D3DXMATRIX rotY, rotX, matWorld;
    D3DXMatrixRotationY(&rotY, secs * D3DX_PI * 0.5f);
    D3DXMatrixRotationX(&rotX, secs * D3DX_PI * 0.35f);
    D3DXMatrixMultiply(&matWorld, &rotX, &rotY);
    g_pd3dDevice->SetTransform(D3DTS_WORLD, &matWorld);
}

void RenderScene()
{
    g_pd3dDevice->Clear(
        0,
        NULL,
        D3DCLEAR_TARGET | D3DCLEAR_ZBUFFER,
        D3DCOLOR_XRGB(16, 16, 32),
        1.0f,
        0);

    g_pd3dDevice->BeginScene();
    g_pd3dDevice->SetRenderState(D3DRS_ZENABLE, TRUE);
    g_pd3dDevice->SetRenderState(D3DRS_LIGHTING, FALSE);
    g_pd3dDevice->SetRenderState(D3DRS_CULLMODE, D3DCULL_NONE);
    g_pd3dDevice->SetStreamSource(0, g_pVB, sizeof(CubeVertex));
    g_pd3dDevice->SetVertexShader(kCubeVertexFvf);
    g_pd3dDevice->SetIndices(g_pIB, 0);
    g_pd3dDevice->DrawIndexedPrimitive(
        D3DPT_TRIANGLELIST,
        0,
        CUBE_VERTEX_COUNT,
        0,
        CUBE_INDEX_COUNT / 3);
    g_pd3dDevice->EndScene();
}

} // namespace

int main()
{
    HRESULT hr;

    printf("Starting cube sample\n");

    hr = InitDevice();
    if (FAILED(hr)) {
        printf("Failed to initialize device (hr=0x%08X)\n", (unsigned)hr);
        Cleanup();
        return 1;
    }

    hr = InitGeometry();
    if (FAILED(hr)) {
        printf("Failed to create geometry (hr=0x%08X)\n", (unsigned)hr);
        Cleanup();
        return 1;
    }

    hr = InitTransforms();
    if (FAILED(hr)) {
        printf("Failed to configure transforms (hr=0x%08X)\n", (unsigned)hr);
        Cleanup();
        return 1;
    }

    InitTime();

    printf("Entering render loop\n");
    while (true) {
        UpdateTime();
        UpdateScene();
        RenderScene();
        g_pd3dDevice->Present(NULL, NULL, NULL, NULL);
    }

    return 0;
}
